---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sourcegraph-data
  namespace: sourcegraph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoekt-webserver-0
  namespace: sourcegraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoekt-webserver-0
  template:
    metadata:
      labels:
        app: zoekt-webserver-0
    spec:
      containers:
        - name: zoekt-webserver-0
          image: sourcegraph/zoekt-webserver:latest
          resources:
            limits:
              cpu: "1"
          ports:
            - containerPort: 6070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoekt-indexserver-0
  namespace: sourcegraph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zoekt-indexserver-0
  template:
    metadata:
      labels:
        app: zoekt-indexserver-0
    spec:
      containers:
        - name: zoekt-indexserver-0
          image: sourcegraph/zoekt-indexserver:latest
          resources:
            limits:
              cpu: "1"
